### ISSUE TITLE
When the variable portion of an array index expression is negative, incorrect code will be generated in some cases.

### ISSUE THREAD

**Issue by sheumann** [byteworksinc/ORCA-C#45]
When the variable portion of an array index expression (the part that is not treated as a compile-time constant) is negative, incorrect code (accessing one bank beyond the correct location) will be generated in some cases.

The following program demonstrates the issue:
```
#pragma optimize 1

char c[100] = {42};

int main(void) {
    int i = -1;
    return c[i+1]; /* should return 42 */
}
```

This error can occur when calling the is* macros in <ctype.h> with an argument of EOF (-1), since they use the index expression `(__ctype)[(c)+1]`. (Issue pointed out by Kelvin Sherlock.)

**Comment by sheumann** [comment]
I believe this only affects accesses to global/static arrays. Also, since it’s undefined behavior to access before the beginning of an object, I think this is only really a problem when the index expression includes a compile-time constant portion that is positive (allowing the variable portion to be negative while still accessing within the array).

**Comment by ksherlock** [comment]
With the large memory model, it generates correct (but horrible) code.

MPW C used this approach (which wouldn't fix the underlying issue but would at least give the correct answer for EOF/-1):

```
/*
 * WARNING:  These macros are not strictly ANSI compliant.  They do not distinguish
 * between EOF (-1) and 0xFF.  However, since only the "C" locale is currently
 * supported, and since in the "C" locale both EOF and 0xFF will fail all these
 * tests, there is no pratical difference.
 */
...
#define isxdigit(c)  ((int)(__p_CType[(unsigned char)(c)] & _HEX))

```

eg,

`#define isxdigit(c)     ((__ctype)[(unsigned char)(c)+1] & __hex)`
