### ISSUE TITLE
loop invariant bug

### ISSUE THREAD

**Issue by ksherlock** [byteworksinc/ORCA-C#50]
```
/* loop invariant removal causes bad code to be generated */
#pragma lint -1
#pragma optimize -1

int getc(void);
#define EOF -1

unsigned s_flag;

int pager(void) {

    unsigned line = 1;
    unsigned col = 1;
    unsigned prev_col = 0;

    while(1) {
        int c;
        c = getc();
        if (c == EOF)
            break;

        if (c == '\n') {
            if (s_flag && col == 1 && prev_col == 1)
                continue;
            prev_col = col;
            col = 1;
        } else { col++; }

    }
    return 0;
}
```

generates this code:
```
; calculating col == 1 and prev_col == 1 outside the loop
000052 000011 |          LDA   $07
000054 000013 |          LDX   #$0000
000057 000016 |          CMP   #$0001
00005A 000019 |          BNE   (pager+$0000001C)
000067 00001B |          INX   
000069 00001C |          TXA   
00006B 00001D |          STA   $09
00006D 00001F |          LDA   $05
00006F 000021 |          LDX   #$0000
000072 000024 |          CMP   #$0001
000075 000027 |          BNE   (pager+$0000002A)
000082 000029 |          INX   
000084 00002A |          TXA   
000086 00002B |          STA   $0B
...
; in the loop...
0000C6 000041 |          LDA   s_flag
0000D3 000044 |          BEQ   (pager+$00000050)
0000E1 000046 |          LDA   $0B
0000E4 000048 |          BEQ   (pager+$00000050)
0000F1 00004A |          LDA   $09
0000F4 00004C |          BEQ   (pager+$00000050)
000101 00004E |          BRA   *-$21
```

Interestingly enough, replacing `while(1)` with a `for(;;)` prevents the loop invariant removal.

ORCA/C 2.2.0 B2

**Comment by sheumann** [comment]
As far as I can tell, the code generated for this is correct (as of ORCA/C 2.2.0 B2).

The loop optimizer treats this code as containing two natural loops, one corresponding to the case where the `continue` statement is executed and one where it isn’t. It sees that `col == 1` and `prev_col == 1` are invariant expressions within the former loop (only), so their calculation can be lifted out of it.

If execution goes to the end  of the full loop, it will branch back to the beginning of the code you show, so the `col == 1` and `prev_col == 1` computations will be updated in that case. Those calculations are only skipped if the `continue` is executed (reflected by the `BRA *-$21` instruction in the code you show).

The optimization isn’t actually beneficial here unless the `continue` case gets executed the vast majority of the time, but the optimizer can’t really assess that, so it goes ahead and performs the optimization. Perhaps some better heuristics could be used to guess if the optimization is really profitable, but for now the optimizer is working as designed, and generating correct code.
