### ISSUE TITLE
debugger symbol table errors with nested structs 

### ISSUE THREAD

**Issue by ksherlock** [byteworksinc/ORCA-C#54]
I'm not sure what the correct behavior is... this can be worked around on the debugger side since it consistent (but none of it was properly documented so I'm not sure if it's a bug or not).

given something like:

```
struct b { int b; };
struct c { int a; struct b b1; struct b b2; };

int test1(void) {
  struct c c;
  return 0;
}
```

The generated symbol table looks like:

```
000086 000014 |          COP   $05
00008A 000016 |          DC    I'60'

struct c c
00008D 000018 |          DC    I4'((test1+$0000006A)+$00000010)'
00009B 00001C |          DC    I4'5'
00009F 000020 |          DC    H'00 0C'
0000A1 000022 |          DC    I2'0'

	int a
	0000A4 000024 |          DC    I4'((test1+$0000006A)+$00000012)'
	0000B2 000028 |          DC    I4'0'
	0000B6 00002C |          DC    H'01 01'
	0000B8 00002E |          DC    I2'0'

	struct b b1
	0000BB 000030 |          DC    I4'((test1+$0000006A)+$00000014)'
	0000C9 000034 |          DC    I4'2'
	0000CD 000038 |          DC    H'01 0C'
	0000CF 00003A |          DC    I2'0'

		int b
		0000D2 00003C |          DC    I4'((test1+$0000006A)+$00000017)'
		0000E0 000040 |          DC    I4'0'
		0000E4 000044 |          DC    H'00 01'
		0000E6 000046 |          DC    I2'0'

	reference to struct b b2
	0000E9 000048 |          DC    I4'((test1+$0000006A)+$00000019)'
	0000F7 00004C |          DC    I4'4'
	0000FB 000050 |          DC    H'00 0D'
	0000FD 000052 |          DC    I2'12' <<< should be 24
```

The second struct, b2, uses a displacement to the first struct. However, the displacement is 12 less than the true displacement (12 less for each nested structure level, in fact).

This may be  fixable by adjusting `symLength` in [`GenSymbol`](https://github.com/byteworksinc/ORCA-C/blob/master/Symbol.pas#L1111) before calling `ExpandStructType`:

```
               symLength := symLength+12; {update length of symbol table}
               ExpandStructType(ip^.itype);
               symLength := symLength-12; {update length of symbol table}
```

**Comment by sheumann** [comment]
This error stems from `GetTypeDisp` recording the wrong displacement for nested structure types because `symLength` has not yet been updated to reflect the size of the entry for the outer structure.

From looking at the code, I think the proposed patch (or something equivalent) would fix the issue. Another option would be to just not record nested structure types for use in later derived-type references (so the full structure definition would be repeated instead).

**Comment by ksherlock** [comment]
I think structures within structures still need to be recorded to handle something like:

```
struct degenerate {

  struct linked_list {
    struct linked_list *next;
  } ll;
};
```

**Comment by sheumann** [comment]
Fixed in a way equivalent to the suggested code.
