### ISSUE TITLE
unsigned math on array pointers

### ISSUE THREAD

**Issue by ksherlock** [byteworksinc/ORCA-C#61]
```
int main(int argc, char *argv[]) {
  argv += 1u;
 return 0;
}
```
This generates a compiler error.

code changes which will compile:
* `char **argv`
* `#pragma memory model 1`
* `#pragma optimize 1`
* `argv += 1`
* `argv += 1ul`
* `argv = argv + 1u`

The actual error occurs in `Gen.pas`, the `GenLod` function.

`char *argv[]` generates this intermediate code:
```
lod(23736) 1:0		; load type 23736
ldci 1			; load const int 1
ldci 4			; load const int 4
umi			; unsigned multiply
ixa			; integer indexed address
...
```

`char **argv`: generates this intermediate code:
```
lodul 1:0
ldci 1
ldci 4
umi
ixa
...
```

(integer and unsigned long variants use the `adl` op) instead of `ixa`.

`ixa` (`GenIxa`) calls `GenTree` which calls `GenLod` which doesn't like the type.  `adl` (`GenAdlSbl`) generates code directly directly so it's not an issue. 

The correct fix is probably to convert "array" parameters into pointers sooner (it also causes inconsistencies in the debugger symbol tables).

**Comment by sheumann** [comment]
Commit 1a2e477 corrects this bug (so I’m marking it as closed), but it doesn’t change the representation of the types of “array” parameters. I agree that would probably be good to do, but it would be a somewhat more involved change, so I haven’t done it for now.

Feel free to file a separate issue about the inconsistencies in debugger symbol tables, if you’d like.

**Comment by sheumann** [comment]
Commits 5b953e2db0 and a6359f67e0 change the handling of “array” parameters so that they are consistently treated as having pointer types. One effect of this is that they are now represented as pointers in the debugger symbol tables.
