### ISSUE TITLE
Orca crash on start with prizm

### ISSUE THREAD

**Issue by GSuser007** [byteworksinc/ORCA-C#68]

**Comment by GSuser007** [comment]
I am using System 6.0.1 with the sanefix.init and both updates crash with the variables window showing at startup.
I using the emulator on a pc but it also crashes on a real GS.

**Comment by sheumann** [comment]
I am aware of a compatibility issue between Prizm and CloseView (the screen magnifying tool in the system software) or other system extensions that affect how graphics are drawn to the screen. If you have anything like that, try disabling it. 

I’m not familiar with the SANE fix init, but I found the following in [an old issue of Shareware Solutions II](https://archive.org/details/Shareware_Solutions_II_Volume_4_Issue_3_1998-04_Kohn_Joe_US/page/n2):

> SANE.Fix is a freeware Initialization File from Seven Hills Software that at the time of its release fixed a problem with the SANE Toolset. However, whatever problem the Init file originally addressed was in an older and now obsolete version of GS/OS. Apple's System programmers have since fixed that problem in System 6.0.1. SANE.Fix is no longer needed and in fact can cause problems if it remains installed. Seven Hills Software does confirm that finding, so if you still have SANE.Fix installed on your system, remove it.

So if that’s what you have, it sounds like you should remove it.

In general, it’s a good idea to try shift-booting to check if any system extensions might be causing a compatibility issue.

If that doesn’t fix the problem, I would need more details about your system configuration and ORCA configuration, as well as the exact circumstances of the crash. Does the problem happen with a fresh ORCA installation (from Opus ][, or freshly installed off the ORCA/C 2.1 disks)?

**Comment by sheumann** [comment]
This may be a compatibility issue as discussed. Even if there was a bug causing this, it would probably be in Prizm and not in the ORCA/C compiler itself. Without further information, it is difficult to say more, so I am going to close this issue.
