### ISSUE TITLE
Compatibility with MAME/MESS?

### ISSUE THREAD

**Issue by roadriverrail** [byteworksinc/ORCA-C#71]
Hi there!  I was curious if anyone had any reports of using ORCA/C with the MAME (more properly MESS) emulator?  I ask because I was poking around at ORCA/C last night on my emulated Apple2GS and couldn't get the Print.cc, the "Hello World" example, to compile at all.  Attempts to compile led to what looked like inifinite loops, and after upgrading the compiler and linker from the latest release here, I instead saw "out of memory" errors, some sort of file I/O error from the linker, etc.

I'd be willing to get more debugging info if I knew how to get it.  I get the impression this is likely some sort of incomplete or incorrect emulation on MAME's part, which I could look into (I ported the Uthernet emulation from VICE to MAME, so I'm somewhat familiar with MAME code), but I'm lacking for a place to even get started.

If anyone's willing to lend some guidance on troubleshooting this, I'll happily do the ground work.

**Comment by bobbimanners** [comment]
Maybe try the same test (with the same disk images) in GSPort or GSPlus or
some other emulator that is not MAME, to determine if this problem is
specific to MAME.  That is my first instinct anyhow.

All the best,
Bobbi

**Comment by roadriverrail** [comment]
So, in poking at this on my GSPort setup, I'm realizing at least one part of the problem is that I thought Print.cc was a console "Hello World" but the "eject a page" comment makes me now understand it was probably intended for a literal printer.  On GSPortX, Ackerman.cc and others work, they compile, etc.  I'll take that back to MAME and try things again.

**Comment by sheumann** [comment]
I have not used ORCA/C under MAME/MESS. I suspect it would likely work, but I second the suggestion of checking if you get the same behavior on a different emulator. GSport/GSplus/Sweet16 should definitely work.

Independent of what emulator you are using, one possible source of problems with the ORCA graphical environment (Prizm) is if you have CloseView (the screen magnifying tool in the system software) installed. Prizm is known to be incompatible with that, so you should remove it if you have it. Other system extensions that affect how the screen is drawn may also cause problems.

**Comment by sheumann** [comment]
Also, as you noticed, Print.cc is intended to be used with an actual printer, and in fact it expects the ORCA printer driver to be installed (as discussed in the manual). If you want to try a simple program that just prints some text on the screen, there are other examples like Finance.cc that will do that (or you can write your own hello world program).

**Comment by roadriverrail** [comment]
Hey, y'all.  Thanks a big one for the forbearance and patience.  I do have both GSPortX and MESS and switch between them a fair amount.  After some noodling around, I found that most of the C samples do compile and run under MESS just fine.  The real stand-out that wasn't compiling was Frame.cc, which still gives an "out of memory" error both by error dialog and in the shell.  I haven't confirmed that particular one on GSPort, but it's really more than plenty to fiddle around with at the moment.

A lot of this is trying to size up my future environment for when I pull the trigger and buy real hardware, but MESS has some really weird quirks in it that I've never really been able to chase down.  For example, telnet programs that use a graphical terminal like Spectrum and Marlene...lack a functional lower-case p.  I know this isn't because MESS has remapped the key, either, because the ORCA/C shell has no problem with lower-case p's, and it works in GSPort (I just find GSPort a bit less stable overall).  This tends to be pretty niche knowledge, and unless I'm going to do some very heavy debugging with some fairly limited experience, asking around is usually the better choice.

**Comment by roadriverrail** [comment]
So, just for the record, I have run this on both GSPort and MESS, and there is definitely something fishy with MESS.  The Frame.cc example compiles to memory and runs just fine under GSPort.  Under MESS, my first attempt crashed to the RAM monitor and my second attempt appeared to go into an endless loop.

I'm guessing I should probably take this up with the MAME team, since it's not y'all's job to support MESS, but I appreciate the feedback while I pinned this down.

**Comment by roadriverrail** [comment]
And, after more careful review, the definitive problem here appears to be one of default memory size.  GSPort defaults to 8MB of RAM; MESS defaults to 1MB.  So, more complicated compiles like Frame.cc were indeed exhausting available memory.  Using `-ramsize 8M` on MESS caused the issue to go away.
