### ISSUE TITLE
Type errors in quickdraw.h

### ISSUE THREAD

**Issue by xandark** [byteworksinc/ORCA-C#77]
I'm not sure I should report this here. I'm noticing that in Libraries:ORCACDefs:quickdraw.h, the declarations for several functions are incorrect. They are listed as:

```
extern pascal void GetPenMask(Mask) inline(0x3304,dispatcher);
extern pascal void SetPenMask(Mask) inline(0x3204,dispatcher);
extern pascal void SetColorTable(Word, ColorTable) inline(0x0E04,dispatcher);
extern pascal void InitColorTable(ColorTable) inline(0x0D04,dispatcher);
extern pascal void GetColorTable(Word, ColorTable) inline(0x0F04,dispatcher);
extern pascal void SetBackPat(Pattern) inline(0x3404,dispatcher);
extern pascal void SetPenPat(Pattern) inline(0x3004,dispatcher);
extern pascal void GetPenPat(Pattern) inline(0x3104,dispatcher);
```

... but they should be _pointers_ that are being passed, not the whole structs:

```
extern pascal void GetPenMask(Mask*) inline(0x3304,dispatcher);
extern pascal void SetPenMask(Mask*) inline(0x3204,dispatcher);
extern pascal void SetColorTable(Word, ColorTablePtr) inline(0x0E04,dispatcher);
extern pascal void InitColorTable(ColorTablePtr) inline(0x0D04,dispatcher);
extern pascal void GetColorTable(Word, ColorTablePtr) inline(0x0F04,dispatcher);
extern pascal void SetBackPat(PatternPtr) inline(0x3404,dispatcher);
extern pascal void SetPenPat(PatternPtr) inline(0x3004,dispatcher);
extern pascal void GetPenPat(PatternPtr) inline(0x3104,dispatcher);
```

I verified these with [IIGS Toolbox Ref Vol 2](https://apple2.gs/downloads/library/Apple%20IIGS%20Toolbox%20Reference%20Volume%202.pdf), pgs:  16-129, 16-233, 16-221, 16-116, 16-158, 16-214, 16-236, 16-131

**Comment by ksherlock** [comment]
The Toolbox Reference II assumes APW C which is K & R.

Example (16-221):
```
extern pascal void SetColorTable(tableNumber,srcTablePtr)
Word tableNumber;
ColorTable srcTablePtr;
```
in ANSI C, that would be `extern pascal void SetColorTable(Word tableNumber, ColorTable srcTablePtr)`

APW C's QuickDraw.h (and ORCA/C's Types.h) `typedef Word ColorTable[16]`, `typedef unsigned char Pattern[32]`, and `typedef unsigned char Mask[8]` so they will be passed as pointers.

**Comment by sheumann** [comment]
As Kelvin noted, `Mask`, `ColorTable`, and `Pattern` are typedefed as array types, and so they will be passed as pointers, following the C convention for "array" parameters. As such, the existing declarations should work correctly, and they also follow the way the types are specified in the Toolbox Reference.

Your alternative versions would work too, but the ORCA/C headers generally use the types given in the Toolbox Reference.

**Comment by xandark** [comment]
Ah, okay, thank you for that, you are right.
