### ISSUE TITLE
A question about identifier lookup implementation

### ISSUE THREAD

**Issue by xandark** [byteworksinc/ORCA-C#78]
I once heard looong ago regarding the slowness of Orca/C that its identifier/label lookup is done linearly rather than using a hash table. True? I've always wondered how much faster Orca/C could've been using hash tables internally.

**Comment by sheumann** [comment]
ORCA/C uses hash tables for its symbol tables (implemented in Symbol.pas).

I have not done detailed performance profiling and I'm sure there are things that could be optimized, but in general I doubt these identifier lookups are a very large portion of overall compilation time.

(Edit: Macro lookup actually uses a hash table too. Linear searches are used within a hash bucket, but each hash bucket should have only a small number of identifiers.)

**Comment by MikeW50** [comment]
None of the ORCA compilers ever used linear lookup. They all used balanced binary trees (early versions) or hash tables (later versions).

Compile speed seemed comparable to other compilers running not eh same processor, but we’ve been spoiled by supercomputers in our phones. :)

Mike

Mike Westerfield
PADI Master Instructor 170184
PADI Tec Deep Instructor
HSA Instructor 4131
505-280-3998

**Comment by xandark** [comment]
Ah-ha! Okay, I'm glad to be corrected! Thanks for the insights.
