### ISSUE TITLE
Code generated by #define causes debug line numbers to not match up

### ISSUE THREAD

**Issue by vavruska** [byteworksinc/ORCA-C#88]
When adding code using #define the debuger does not bring you to the right line. It might be related to bug #40.  Here is some code to demonstrate the issue.  
Also, if I generate the source listing there appears to be a number of blank lines at the end of the buffer that are not included in the source files. This may give a clue or it may not be related.   

#include <stdio.h>

#define mycode(x) printf("%d\n",x); x++

#pragma debug 2
void sub1(int i) {
	mycode(i);
	mycode(i);
}
#pragma debug 0

#pragma debug 2
void sub2(int *i) {
	mycode((*i));
	mycode((*i));
}
#pragma debug 0

int main (int argc, char *argv[]) {
	int a = 1;
	
	mycode(a);
	mycode(a);
	sub1(a);
	sub2(&a);
	mycode(a);
	mycode(a);

	return 0;
}

**Comment by ksherlock** [comment]
That sounds like a golden gate problem. The most recent version has a bug where it collapses newlines and screws up the line number (I was trying to fix msdos-style CR/LF combos and screwed it up).

**Comment by vavruska** [comment]
I can confirm that this is a GoldenGate issue.  I have recompiled from the orca shell and it is now working as expected.  Sorry for the alarm
